---
title: 'Week 2 Problem Set: Statistics and Time Series'
author: "Andrew Nalundasan"
date: "10/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Course: OMSBA 5305
# Purpose: Week 2 Problem Set: Statistics and Time Series
# Date: October 8, 2021
# Author: Andrew Nalundasan
```

```{r}
# load libraries
library(readxl)
```

# read-in the data
```{r}
USGDP <- read_excel("../02_raw_data/USGDP-1.xlsx")
```

# make the dataset a time-series
```{r}
Y <- ts(USGDP$GDP, frequency = 4, start = c(2001, 1))
Y
```

# plot the data
```{r}
plot(Y)
```

# log-ify the time-series data
```{r}
y <- log(Y)
y
```

# plot the log of the series
```{r}
plot(y)
```

# calculate the growth rate
```{r}
g1t <- 100 * diff(Y) / stats::lag(Y)
```

# view results of g1t
```{r}
g1t
```

# calculate growth rate of nominal GDP taking the first log-differences (in %)
```{r}
g2t <- 100 * diff(y)
```

# plot g2t and compare to g1t
```{r}
plot(g1t)
plot(g2t)
```

# view results of g2t
```{r}
g2t
```

# calculate statistical information of g2t
```{r}
mean(g2t)
var(g2t)
```

# calculate ACF for g2t
```{r}
acf(g2t, lag.max=4, plot=FALSE)
```

# plot ACF for g2t
```{r}
acf(g2t,lag.max=4)
```





